// Runs on Netlify at build time: writes env.js from the site's environment variables.
import { writeFileSync } from 'node:fs';
const pick = (...names) => { for (const n of names) if (process.env[n]) return process.env[n]; return ''; };
const url = pick('SUPABASE_URL', 'VITE_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_URL', 'PUBLIC_SUPABASE_URL');
const anon = pick('SUPABASE_ANON_KEY', 'SUPABASE_KEY', 'VITE_SUPABASE_ANON_KEY', 'NEXT_PUBLIC_SUPABASE_ANON_KEY', 'PUBLIC_SUPABASE_ANON_KEY');
if (!url || !anon) console.warn('build-env: SUPABASE_URL / SUPABASE_ANON_KEY not set — dashboard will run in demo mode');
if (process.env.RESEND_API_KEY) console.warn('build-env: RESEND_API_KEY is ignored here on purpose — it is a secret and belongs in Supabase edge-function secrets, never in the browser');
writeFileSync('env.js', `// generated by build-env.mjs at deploy — do not edit\nexport const SUPABASE_URL = ${JSON.stringify(url)};\nexport const SUPABASE_ANON_KEY = ${JSON.stringify(anon)};\n`);
console.log('build-env: env.js written', url ? '(' + url + ')' : '(empty)');
